version: "3.9"
services:
    apiServer:
        env_file:
            - ./server/.env.prod
        image: "uflock/emma-app-api-server"
        build:
            context: ./server
            dockerfile: Dockerfile
            target: production
        ports:
            - "3000:3000"
        networks:
            - frontend
            - backend
    mongo-db:
        image: "mongo"
        command: mongod --quiet --logpath /dev/null
        ports:
            - "27017:27017"
        networks:
            - backend
networks:
    frontend:
    backend:
